### ISSUE TITLE
Missing menu overflow buttons on sway

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/sway-gtk-menu#1]
When the (sub)menu height exceeds the screen height, on top and bottom edges the buttons to scroll the content up/down should appear. The content should also be scrollable with the mouse scroller.  It works well on i3, but not on sway. Initially I thought it didn't work at all on Wayland, as many other things. BUT the buttons appear to me occasionally, especially when running the script on PyCharm. This could indicate differences between virtual and real environment, but I couldn't find any. Does anyone have an idea?

![menu-overflow](https://user-images.githubusercontent.com/20579136/71886331-4b56cd00-313c-11ea-9850-040e2424c494.png)

**Comment by nwg-piotr** [comment]
Workaround added in #5.

**Comment by tmccombs** [comment]
Is there a bug filed with sway or gtk for this?

**Comment by nwg-piotr** [comment]
Couldn't find any. Since sway 1.3 is right behind the corner, I decided to wait and see what happens.
