### ISSUE TITLE
Possibly missing python module?

### ISSUE THREAD

**Issue by morten-b** [nwg-piotr/sway-gtk-menu#13]
After installing from the AUR and running `sgtk-menu -f -a` it returns the following error: 
```
Traceback (most recent call last):
  File "menu.py", line 25, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
```
Running Arch and Sway 1.2

Please let me know if further debugging info is needed.

**Comment by nwg-piotr** [comment]
Could you try installing the `python-cairo` package? I used to think it should be installed as a dependency to dependencies, but apparently I was wrong.

**Comment by morten-b** [comment]
> Could you try installing the `python-cairo` package? 

This fixes the problem, thanks!

**Comment by nwg-piotr** [comment]
Thanks for pointing this out. I'll update PKGBUILD in AUR in the evening.

**Comment by nwg-piotr** [comment]
Done.
