### ISSUE TITLE
swaymsg directory missing when trying in i3wm|manjaro

### ISSUE THREAD

**Issue by vdg0** [nwg-piotr/sway-gtk-menu#19]
Awesome project!
I installed from AUR in manjaro, added this two lines an i3/config:

for_window [title="~sgtk-menu"] border none, floating enable
and the bindsym to test:
bindsym Mod1+F1 exec --no-startup-id sgtk-menu -f -a

But when I try to running sgtk-menu, error:

https://pastebin.com/19gJs9Ss

**Comment by nwg-piotr** [comment]
Thanks! Will be fixed later tonight. I have no machine w/o sway installed, that's why it stood unnoticed.

**Comment by nwg-piotr** [comment]
What's on the "experiments" branch ATM may be insufficient for the window to behave well on i3. I'll change it as soon as I put my hand on a Linux machine.

**Comment by vdg0** [comment]
Seems like needs a little more of l0v3:

~/tools/sgtk-menu >>> python sgtk-menu/menu.py -f -a         ±[origin/experiments]
Traceback (most recent call last):
  File "sgtk-menu/menu.py", line 48, in <module>
    swaymsg: bool = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'swaymsg'

![image](https://user-images.githubusercontent.com/246793/72550295-2e737580-3871-11ea-814a-9a818ce04918.png)

**Comment by nwg-piotr** [comment]
It took me awhile, as I needed to finish changes to another part of code before publishing. Hopefully it's going not to crash any longer. Please close the issue if it works well for you, or let me know if it doesn't. AUR package updated to 0.5.0.

**Comment by vdg0** [comment]
![image](https://user-images.githubusercontent.com/246793/72635981-d4d87d00-393c-11ea-91de-565b06e02701.png)
Working like a champ!
Good work nwg-piotr! :) Thanks

**Comment by nwg-piotr** [comment]
Thanks again for reporting. I was likely not to notice the issue on any of my Linux installs.
