### ISSUE TITLE
[GUI] New display with too many results

### ISSUE THREAD

**Issue by tmarti2** [nwg-piotr/sway-gtk-menu#37]
A picture is worth a thousand words.
![image](https://user-images.githubusercontent.com/32908972/73656863-4c264480-4691-11ea-8edb-b7b25c7c03d6.png)
Is there a way so that the space above the search box only appears when you actually start to scroll down? It is quite ugly when the display is changing while typing...

**Comment by nwg-piotr** [comment]
Nope. This is a GTK behaviour, which has nothing to do with my code.
