### ISSUE TITLE
Please add an option to hold (--hold)

### ISSUE THREAD

**Issue by sauraveldho** [nwg-piotr/sway-gtk-menu#52]
I'm currently thinking of executing sgtk-menu using -p, -af on my custom JSON files to use as context menus (right click menus) for waybar modules...
Currently, I can use it like a usual menu, but if there's a --hold option, after selecting one button from menu, it won't exit (especially required if I use it for backlight and volume increase).

Another option I'd like you guys to add with this option is an option to exit if mouse exits the window of the menu. That is, after mouse pointer enters the menu, if the mouse pointer exits it's window, exit the menu. That way, I'd have an option to place hovering menus( menus while hovering over waybar modules, coz there's an option to execute command while hovering over modules too).

And thank you for making this, this is the best widget I've seen of Wayland. I absolutely love it.

**Comment by nwg-piotr** [comment]
Haven't yet checked, however:

1. to close a menu on focus out event should be possible, but...
2. leaving a Gtk.Menu widget open after clicking a selected Gtk.MenuItem is probably impossible.

There are other [Gtk widgets](https://developer.gnome.org/gtk3/stable/ch03.html) to perform action as described, to necessarily the menu widget.
