### ISSUE TITLE
Apps without ```Categories``` ignored

### ISSUE THREAD

**Issue by Evo221** [nwg-piotr/sway-gtk-menu#53]
Thanks for writing and releasing sgtk-menu. I've been enjoying using it since you announced it on Reddit. This is an old bug that that I've been working around by editing my desktop files, but thought I may be worthwhile bringing it to your attention.

Desktop entries (```*.desktop``` files) without a ```Categories``` field are ignored by sgtk-menu. From a quick read of ```list_entries()``` in
```sgtk_menu/menu.py``` I can see from https://github.com/nwg-piotr/sgtk-menu/blob/ceb821ab400ff7a0c1eb32d241e3999109cdcfa5/sgtk_menu/menu.py#L504
that if ```_categories``` is still ```''``` no ```DesktopEntry()``` object will be made. 

Perhaps a fix could be to just set _categories to 'Other' where it is declared earlier in ```list_entries()```. 
https://github.com/nwg-piotr/sgtk-menu/blob/ceb821ab400ff7a0c1eb32d241e3999109cdcfa5/sgtk_menu/menu.py#L465

This  *almost* works for me: sgtk-menu will now find and launch *.desktop entries without a ```Categories``` field but for some reason the desktop entry icon is not shown.

**Comment by nwg-piotr** [comment]
I must admit, that in real life I only use grid and bar from my [another project](https://github.com/nwg-piotr/nwg-launchers), so the issue remained unnoticed on my side. I'll try to find a solution tonight.

**Comment by nwg-piotr** [comment]
Could you check if the current `master` works well? And reopen the issue if it does not?

**Comment by Evo221** [comment]
Yes this seems to have fixed it. However since you pointed me to nwg-launchers I've started using nwggrid instead.

**Comment by nwg-piotr** [comment]
LOL, good choice! 🙂
