### ISSUE TITLE
sgtk-menu opens in top right corner instead of centre

### ISSUE THREAD

**Issue by dchinmay2** [nwg-piotr/sway-gtk-menu#55]
**Describe the bug**
Title. (It opens in floating mode though)

**To Reproduce**
Enter `sgtk-dmenu` in kitty

**Expected behavior**
It opens in the centre of the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/36493671/104115952-92bcfe00-533a-11eb-8f43-6de37268598d.png)

**Environment (please complete the following information):**
 - Linux distribution: arch
 - Window Manager: sway
 - Window Manager version: 1.5.1
 - Python version: 3.9.1
 - sgtk-menu version 1.4.1

**Comment by nwg-piotr** [comment]
You seem to have missed the `-c` argument.

![image](https://user-images.githubusercontent.com/20579136/104125122-03711400-5355-11eb-846f-9e2c2a142256.png)

```text
$ sgtk-dmenu -h
usage: sgtk-dmenu [-h] [-b | -c | -p] [-a | -af AF] [-s S] [-w W] [-d D] [-o O] [-t T] [-y Y] [-css CSS]

GTK dmenu for sway, i3 and some other WMs

optional arguments:
  -h, --help     show this help message and exit
  -b, --bottom   display menu at the bottom
  -c, --center   center menu on the screen
  -p, --pointer  display at mouse pointer (not-sway only)
  -a, --append   append custom menu from /home/piotr/.config/sgtk-menu/appendix
  -af AF         append custom menu from /home/piotr/.config/sgtk-menu/<AF>
  -s S           menu icon size (min: 16, max: 48, default: 20)
  -w W           menu width in px (integer, default: screen width / 8)
  -d D           menu delay in milliseconds (default: 100; sway & i3 only)
  -o O           overlay opacity (min: 0.0, max: 1.0, default: 0.3; sway & i3 only)
  -t T           lines limit (default: 20)
  -y Y           y offset from edge to display menu at
  -css CSS       use alternative /home/piotr/.config/sgtk-menu/<CSS> style sheet instead of style.css
```

If you want my advice: for dmenu and application grid use `nwgdmenu` and `nwggrid` from [nwg-launchers](https://github.com/nwg-piotr/nwg-launchers). They look the same, but were written in C++, and are still under active development. The python version is quite far behind.
